#This workflow ensures that on every push or pull request to the main branch, specifically affecting the deployment/web-service/** directory, the following actions are performed:

#The code is checked out.
#Python 3.9 is set up.
#Dependencies are installed in a virtual environment.
#Unit tests are executed using pytest.
#This setup helps in maintaining code quality by running automated tests on specified triggers, ensuring that changes do not break the existing functionality.

name: CI Tests

on:
  push:
    branches:
      - main
    paths:
      - 'deployment/web-service/**'
  pull_request:
    branches:
      - main
    paths:
      - 'deployment/web-service/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          source venv/bin/activate
          pytest -v --tb=short
